#!/usr/bin/bash

SYSFS=/sys/class/power_supply
BATTERY=BAT0
MAINS=AC0

# https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/power/power_supply_class.txt
# power is measured in microwatts
POWER_NOW=$(<"$SYSFS/$BATTERY/power_now")
# energy is measured in microwatt-hours
ENERGY_NOW=$(<"$SYSFS/$BATTERY/energy_now")
ENERGY_FULL=$(<"$SYSFS/$BATTERY/energy_full")
ENERGY_FULL_DESIGN=$(<"$SYSFS/$BATTERY/energy_full_design")
# 1 if mains is plugged in, 0 otherwise
AC_ON=$(<"$SYSFS/$MAINS/online")

# this is equivalent to "$SYSFS/$BATTERY/capacity"
# however, since we need the energy values anyway, i prefer to calculate it here
printf "%s%%" "$(( ENERGY_NOW * 100 / ENERGY_FULL ))"
if (( AC_ON )) ; then
  if (( POWER_NOW )) ; then
    printf " charging in %smin" "$(( (ENERGY_FULL - ENERGY_NOW) * 60 / POWER_NOW ))"
  else
    printf " not charging"
  fi
else
  if (( POWER_NOW )) ; then
    printf " discharging in %smin" "$(( ENERGY_NOW * 60 / POWER_NOW ))"
  else
    # TODO: can this ever actually happen?
    printf " not discharging"
  fi
fi
printf " (%s%% of design)\n" "$(( ENERGY_FULL * 100 / ENERGY_FULL_DESIGN ))"
