#!/usr/bin/bash

if [[ "${2}" == 'DISCONNECTED' ]] ; then
  printf -v msg '%s disconnected' "$1"
else
  # TODO: fetch network's SSID instead of using WPA_ID_STR
  # would have to parse the output of:
  #   wpa_cli -p "${WPA_CTRL_DIR}" -i "${1}" list_networks
  printf -v msg '%s connected to %s (%s)' "$1" "${WPA_ID_STR}" "${WPA_ID}"
fi

notify-send -t 3000 'wpa_supplicant' "$msg"
